### ISSUE TITLE
welcomemat problems

### ISSUE THREAD

**Issue by cyraxan** [91loocekaj/vs-usefulstuff#4]
welcome mats seems to have unusual enormous high CPU, mem and tick usage on server and client
few mats could notable drop FPS on solid PC, several mats can easy turn video into slideshow
![image](https://user-images.githubusercontent.com/34022944/154012126-51433c5b-58a0-4c2a-968d-d060b9557884.png)

**Comment by 91loocekaj** [comment]
This has been addressed with release 2.3.1.
